Controllers/AccountTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using e_loanApp.Models;

namespace e_loanApp.Controllers
{
    public class AccountTablesController : Controller
    {
        private eLoan_ApplicationEntities1 db = new eLoan_ApplicationEntities1();

        // GET: AccountTables
        public ActionResult Index()
        {
            var accountTables = db.AccountTables.Include(a => a.UserTable);
            return View(accountTables.ToList());
        }

        // GET: AccountTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountTable accountTable = db.AccountTables.Find(id);
            if (accountTable == null)
            {
                return HttpNotFound();
            }
            return View(accountTable);
        }

        // GET: AccountTables/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.UserTables, "UserId", "User_First_Name");
            return View();
        }

        // POST: AccountTables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Account_Id,Account_name,Account_SortCode,Account_number,UserId,Date_Created")] AccountTable accountTable)
        {
            if (ModelState.IsValid)
            {
                db.AccountTables.Add(accountTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.UserTables, "UserId", "User_First_Name", accountTable.UserId);
            return View(accountTable);
        }

        // GET: AccountTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountTable accountTable = db.AccountTables.Find(id);
            if (accountTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.UserTables, "UserId", "User_First_Name", accountTable.UserId);
            return View(accountTable);
        }

        // POST: AccountTables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Account_Id,Account_name,Account_SortCode,Account_number,UserId,Date_Created")] AccountTable accountTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(accountTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.UserTables, "UserId", "User_First_Name", accountTable.UserId);
            return View(accountTable);
        }

        // GET: AccountTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountTable accountTable = db.AccountTables.Find(id);
            if (accountTable == null)
            {
                return HttpNotFound();
            }
            return View(accountTable);
        }

        // POST: AccountTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AccountTable accountTable = db.AccountTables.Find(id);
            db.AccountTables.Remove(accountTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/RoleMappingTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using e_loanApp.Models;

namespace e_loanApp.Controllers
{
    public class RoleMappingTablesController : Controller
    {
        private eLoan_ApplicationEntities1 db = new eLoan_ApplicationEntities1();

        // GET: RoleMappingTables
        public ActionResult Index()
        {
            var roleMappingTables = db.RoleMappingTables.Include(r => r.RoleTable).Include(r => r.UserTable);
            return View(roleMappingTables.ToList());
        }

        // GET: RoleMappingTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoleMappingTable roleMappingTable = db.RoleMappingTables.Find(id);
            if (roleMappingTable == null)
            {
                return HttpNotFound();
            }
            return View(roleMappingTable);
        }

        // GET: RoleMappingTables/Create
        public ActionResult Create()
        {
            ViewBag.RoleId = new SelectList(db.RoleTables, "RoleId", "Role");
            ViewBag.UserId = new SelectList(db.UserTables, "UserId", "User_First_Name");
            return View();
        }

        // POST: RoleMappingTables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoleMappingId,UserId,RoleId")] RoleMappingTable roleMappingTable)
        {
            if (ModelState.IsValid)
            {
                db.RoleMappingTables.Add(roleMappingTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RoleId = new SelectList(db.RoleTables, "RoleId", "Role", roleMappingTable.RoleId);
            ViewBag.UserId = new SelectList(db.UserTables, "UserId", "User_First_Name", roleMappingTable.UserId);
            return View(roleMappingTable);
        }

        // GET: RoleMappingTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoleMappingTable roleMappingTable = db.RoleMappingTables.Find(id);
            if (roleMappingTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.RoleId = new SelectList(db.RoleTables, "RoleId", "Role", roleMappingTable.RoleId);
            ViewBag.UserId = new SelectList(db.UserTables, "UserId", "User_First_Name", roleMappingTable.UserId);
            return View(roleMappingTable);
        }

        // POST: RoleMappingTables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoleMappingId,UserId,RoleId")] RoleMappingTable roleMappingTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roleMappingTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(db.RoleTables, "RoleId", "Role", roleMappingTable.RoleId);
            ViewBag.UserId = new SelectList(db.UserTables, "UserId", "User_First_Name", roleMappingTable.UserId);
            return View(roleMappingTable);
        }

        // GET: RoleMappingTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoleMappingTable roleMappingTable = db.RoleMappingTables.Find(id);
            if (roleMappingTable == null)
            {
                return HttpNotFound();
            }
            return View(roleMappingTable);
        }

        // POST: RoleMappingTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RoleMappingTable roleMappingTable = db.RoleMappingTables.Find(id);
            db.RoleMappingTables.Remove(roleMappingTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UserTables1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using e_loanApp.Models;

namespace e_loanApp.Controllers
{
    public class UserTables1Controller : Controller
    {
        private eLoan_ApplicationEntities1 db = new eLoan_ApplicationEntities1();

        // GET: UserTables1
        public ActionResult Index()
        {
            var userTables = db.UserTables.Include(u => u.AccountTable).Include(u => u.RoleTable).Where(a => a.RoleId != 1).Where(a => a.RoleId != 2);
            return View(userTables.ToList());
        }

        // GET: UserTables1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTable userTable = db.UserTables.Find(id);
            if (userTable == null)
            {
                return HttpNotFound();
            }
            return View(userTable);
        }

        // GET: UserTables1/Create
        public ActionResult Create()
        {
            ViewBag.AccountId = new SelectList(db.AccountTables, "Account_Id", "Account_name");
            ViewBag.RoleId = new SelectList(db.RoleTables, "RoleId", "Role");
            return View();
        }

        // POST: UserTables1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "UserPassword,IsEmailVerified,ActivationCode,Date_Created")] UserTable userTable, RoleMappingTable roleMappingTable)
        {
            if (ModelState.IsValid)
            {
                userTable.RoleId = 3;
               // userTable.AccountId = 
                db.UserTables.Add(userTable);
                db.SaveChanges();

                var userID = db.UserTables.FirstOrDefault(x => x.Email_Address == userTable.Email_Address).UserId;
                roleMappingTable.RoleId = 3;
                roleMappingTable.UserId = userID;
                db.RoleMappingTables.Add(roleMappingTable);
                db.SaveChanges();

              //  accountTable.UserId = userID;
                //accountTable.Account_SortCode = userTable.sortCode;
                //accountTable.Account_name = userTable.User_First_Name + ' ' + userTable.User_Last_Name;
                //accountTable.Account_number = userTable.acctNumber;
                //db.AccountTables.Add(accountTable);
                //db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.AccountId = new SelectList(db.AccountTables, "Account_Id", "Account_name", userTable.AccountId);
            ViewBag.RoleId = new SelectList(db.RoleTables, "RoleId", "Role", userTable.RoleId);
            return View(userTable);
        }

        // GET: UserTables1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTable userTable = db.UserTables.Find(id);
            if (userTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.AccountId = new SelectList(db.AccountTables, "Account_Id", "Account_name", userTable.AccountId);
            ViewBag.RoleId = new SelectList(db.RoleTables, "RoleId", "Role", userTable.RoleId);
            return View(userTable);
        }

        // POST: UserTables1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Exclude = "UserPassword,IsEmailVerified,ActivationCode,Date_Created")] UserTable userTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userTable).State = EntityState.Modified;
                db.Entry(userTable).Property(x => x.UserPassword).IsModified = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AccountId = new SelectList(db.AccountTables, "Account_Id", "Account_name", userTable.AccountId);
            ViewBag.RoleId = new SelectList(db.RoleTables, "RoleId", "Role", userTable.RoleId);
            return View(userTable);
        }

        // GET: UserTables1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTable userTable = db.UserTables.Find(id);
            if (userTable == null)
            {
                return HttpNotFound();
            }
            return View(userTable);
        }

        // POST: UserTables1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserTable userTable = db.UserTables.Find(id);
            db.UserTables.Remove(userTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Admin/AdminPage.cshtml
@model IEnumerable<e_loanApp.Models.Transaction_Table>
@{
    ViewBag.Title = "AdminPage";
}

<div class="">
    <div class="row">
        <!-- /.navbar-collapse -->
        <!-- overlay to close sidebar on small screens -->
        <div class="w-100 vh-100 position-fixed overlay d-none" id="sidebar-overlay"></div>
        <!-- note: in the layout margin auto is the key as sidebar is fixed -->
        <div class="col-md-9 col-lg-12 ml-md-auto px-lg-5 py-lg-5 w-auto">
            <!-- top nav -->
            <nav class="w-100 d-flex px-4 py-2 mb-4 bg-white shadow-sm">
                <!-- close sidebar -->
                <button class="btn py-0" id="open-sidebar">
                    <span class="bi bi-person text-primary h3">  Welcome @HttpContext.Current.User.Identity.Name</span>
                </button>
                <!--<div class="dropdown ml-auto">
                    <button class="btn py-0 d-flex align-items-center" id="logout-dropdown" data-toggle="dropdown" aria-expanded="false">
                        <span>
                            $ @ViewBag.Total
                        </span>-->
                        @*<span class="bi bi-person text-primary h4"></span>
                        <span class="bi bi-chevron-down ml-1 mb-2 small"></span>*@
                    <!--</button>-->
                    @*<div class="dropdown-menu dropdown-menu-right border-0 shadow-sm" aria-labelledby="logout-dropdown">
                        <a class="dropdown-item" href="#">Logout</a>
                        <a class="dropdown-item" href="#">Settings</a>
                    </div>*@
                <!--</div>-->
            </nav>
            <!-- main content -->
            <main class="container-fluid">
                <section class="row">
                    <div class="col-md-6 col-lg-4">
                        <!-- card -->
                        <article class="p-4 rounded shadow-sm border-left mb-4 fourSections" style="border-left: 1px solid #01d28e !important; height: 80px;">
                            <a href="#" class="d-flex align-items-center linkDashBoard" style="left: 15%; position: absolute;">
                                <span class="h5 text-success" style="height: 35px; font-size: 17px;">  @Html.ActionLink("Pending Loan", "ViewPendingLoan", "Admin")</span>
                            </a>
                        </article>
                    </div>
                    <div class="col-md-6 col-lg-4">
                        <article class="p-4 rounded shadow-sm border-left mb-4 fourSections" style="border-left: 1px solid #01d28e !important; height: 80px;">
                            <a href="#" class="d-flex align-items-center linkDashBoard" style="left: 15%; position: absolute;">
                                <span class=" h5 text-success" style="height: 35px; font-size: 17px;">  @Html.ActionLink("Manage User", "Index", "UserTables1")</span>
                            </a>
                        </article>
                    </div>
                </section>
                <!--<section class="row">
                    <div class="col-md-6 col-lg-4">-->
                        <!-- card -->
                        <!--<article class="p-4 rounded shadow-sm border-left mb-4 fourSections" style="border-left: 1px solid #01d28e !important; height: 80px;">
                            <a href="#" class="d-flex align-items-center linkDashBoard" style="left: 15%; position: absolute;">
                                <span class="h5 text-success" style="height: 35px; font-size: 17px;">  @Html.ActionLink("Manage Role", "Index", "RoleMappingTables")</span>
                            </a>
                        </article>
                    </div>
                    <div class="col-md-6 col-lg-4">
                        <article class="p-4 rounded shadow-sm border-left mb-4 fourSections" style="border-left: 1px solid #01d28e !important; height: 80px;">
                            <a href="#" class="d-flex align-items-center linkDashBoard" style="left: 15%; position: absolute;">
                                <span class="h5 text-success" style="height: 35px; font-size: 17px;">  @Html.ActionLink("Manage Account", "Index", "AccountTables")</span>
                            </a>
                        </article>
                    </div>
                </section>-->

                <div class="row">

                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Transaction Table</h3>

                                @*<div class="card-tools">
                                    <div class="input-group input-group-sm" style="width: 150px;">
                                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-default">
                                                <i class="fas fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>*@
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body table-responsive p-0">
                                <table class="table table-hover text-nowrap">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Name</th>
                                            <th>Amount</th>
                                            <th>Status</th>
                                            <th>Reason</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{ int rowNo = 0; }
                                        @foreach (var history in Model)
                                        {
                                        <tr>
                                            <td>@(rowNo += 1)</td>
                                            <td>@Html.DisplayFor(modelItem => history.Receiver_Account_name)</td>
                                            <td>$@Html.DisplayFor(modelItem => history.amount)</td>
                                            <td><span class="tag tag-success">@Html.DisplayFor(modelItem => history.Transaction_status)</span></td>
                                            <td>Over draft</td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                @*</div>*@
            </main>
        </div>
    </div>
</div>

Views/Admin/ApproveLoan.cshtml
@model e_loanApp.Models.Transaction_Table

@{
    ViewBag.Title = "ApproveLoan";
}

<h2>ApproveLoan</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction_Table</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Txn_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Receiver_Account_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Receiver_Account_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Receiver_Account_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Receiver_SortCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Receiver_SortCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Receiver_SortCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reciever_Accountnum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reciever_Accountnum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reciever_Accountnum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Transaction_Purpose, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Transaction_Purpose, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Transaction_Purpose, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Transaction_status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Transaction_status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Transaction_status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Receiver_Bank, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Receiver_Bank, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Receiver_Bank, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Transaction_Approved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Transaction_Approved)
                    @Html.ValidationMessageFor(model => model.Transaction_Approved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Transaction_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Transaction_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Transaction_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.account_Id, "account_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("account_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.account_Id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.User_Id, "User_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("User_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.User_Id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.Role_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role_Id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Role_Level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role_Level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role_Level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Receiver_Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Receiver_Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Receiver_Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpenPayUserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpenPayUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpenPayUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>